name: Sync starter Medusa template

# cronjob trigger every day at 08:00
on: 
  schedule:
  - cron:  "0 8 * * *"
  workflow_dispatch:

jobs:
  sync-repo-with-its-template:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The sync job is started"
      - name: Checkout
        uses: actions/checkout@v3
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v0.8.0
        with:
          source_repo_path: medusajs/nextjs-starter-medusa
          upstream_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "Template synced ${{ job.status }}"
